api_key: None #  YOUR_API_KEY_HERE  # Replace with your actual Gemini API key if you need to - the default is to load it from your ~/.env file
model_name: "gemini-2.5-flash-preview-04-17" # Or other compatible model
verbose: false
default_thinking_budget: 256 # Default token budget for tool use / thinking
PDFS_TO_CHAT_WITH_DIRECTORY: "PDFS/" # Relative path from project root
SAVED_CONVERSATIONS_DIRECTORY: "SAVED_CONVERSATIONS/" # Relative path from project root
PAPER_DB_PATH: "processed_papers/metadata.db" # Relative path for paper database
PAPER_BLOBS_DIR: "processed_papers/blobs/"    # Relative path for text blobs
MAX_PDF_CONTEXT_LENGTH: None # Max chars from PDF to prepend
